export const tiposClases = {
  BUSCAR_CLASES_PENDIENTE: "BUSCAR_CLASES_PENDIENTE",
  BUSCAR_CLASES_TERMINADA: "BUSCAR_CLASES_TERMINADA",
  BUSCAR_CLASES_RECHAZADA: "BUSCAR_CLASES_RECHAZADA",
  NUEVA_CLASE: "NUEVA_CLASE",
  GUARDAR_CLASE: "GUARDAR_CLASE",
  BUSCAR_CLASES_POR_ID_PENDIENTE: "BUSCAR_CLASES_POR_ID_PENDIENTE",
  BUSCAR_CLASES_POR_ID_TERMINADA: "BUSCAR_CLASES_POR_ID_TERMINADA",
  BUSCAR_CLASES_POR_ID_RECHAZADA: "BUSCAR_CLASES_POR_ID_RECHAZADA",
  ACTUALIZAR_CLASE: "ACTUALIZAR_CLASE",
  ELIMINAR_CLASE: "ELIMINAR_CLASE",
};

export const tiposClientes = {
  BUSCAR_CLIENTES_PENDIENTE: "BUSCAR_CLIENTES_PENDIENTE",
  BUSCAR_CLIENTES_TERMINADA: "BUSCAR_CLIENTES_TERMINADA",
  BUSCAR_CLIENTES_RECHAZADA: "BUSCAR_CLIENTES_RECHAZADA",
  NUEVO_CLIENTE: "NUEVO_CLIENTE",
  GUARDAR_CLIENTE: "GUARDAR_CLIENTE",
  BUSCAR_CLIENTES_POR_ID_PENDIENTE: "BUSCAR_CLIENTES_POR_ID_PENDIENTE",
  BUSCAR_CLIENTES_POR_ID_TERMINADA: "BUSCAR_CLIENTES_POR_ID_TERMINADA",
  BUSCAR_CLIENTES_POR_ID_RECHAZADA: "BUSCAR_CLIENTES_POR_ID_RECHAZADA",
  ACTUALIZAR_CLIENTE: "ACTUALIZAR_CLIENTE",
  ELIMINAR_CLIENTE: "ELIMINAR_CLIENTE",
};

export const tiposTurnos = {
  BUSCAR_TURNOS_PENDIENTE: "BUSCAR_TURNOS_PENDIENTE",
  BUSCAR_TURNOS_TERMINADA: "BUSCAR_TURNOS_TERMINADA",
  BUSCAR_TURNOS_RECHAZADA: "BUSCAR_TURNOS_RECHAZADA",
  NUEVO_TURNO: "NUEVO_TURNO",
  GUARDAR_TURNO: "GUARDAR_TURNO",
  BUSCAR_TURNOS_POR_ID_PENDIENTE: "BUSCAR_TURNOS_POR_ID_PENDIENTE",
  BUSCAR_TURNOS_POR_ID_TERMINADA: "BUSCAR_TURNOS_POR_ID_TERMINADA",
  BUSCAR_TURNOS_POR_ID_RECHAZADA: "BUSCAR_TURNOS_POR_ID_RECHAZADA",
  ACTUALIZAR_TURNO: "ACTUALIZAR_TURNO",
  ELIMINAR_TURNO: "ELIMINAR_TURNO",
};
